apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitops-deployment
  labels:
    env: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      env: dev
  template:
    metadata:
      labels:
        env: dev
    spec:
      containers:
      - name: gitops
        image: nginx
        ports:
        - containerPort: 80
