apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitops-deployment
  labels:
    env: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      env: dev
  template:
    metadata:
      labels:
        env: dev
    spec:
      containers:
      - name: gitops
        image: 584342841319.dkr.ecr.us-east-1.amazonaws.com/ecr-repo-random-123456:2022-12-09.22.40.45.228dc0fd
        ports:
        - containerPort: 8080
