apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  selector:
    matchLabels:
      app: app-deployment
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: app-deployment
    spec:
      containers:
      - name: app-deployment
        image: 832760563441.dkr.ecr.us-east-1.amazonaws.com/ecr-repo-random-123456:2022-12-09.05.39.08.4824a4ec
        ports:
        - containerPort: 80
