apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  selector:
    matchLabels:
      app: app-deployment
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: app-deployment
    spec:
      containers:
      - name: app-deployment
        image: 328916801733.dkr.ecr.us-east-1.amazonaws.com/ecr-repo-random-123456:2022-12-08.06.07.33.c662c88e
        ports:
        - containerPort: 80
