apiVersion: apps/v1
kind: Deployment
metadata:
  name: eks-devops-deployment
  labels:
    app: eks-devops
spec:
  replicas: 2
  selector:
    matchLabels:
      app: eks-devops
  template:
    metadata:
      labels:
        app: eks-devops
    spec:
      containers:
        - name: eks-devops
          image: 659304862788.dkr.ecr.us-east-1.amazonaws.com/ecr-repo-random-123456:2022-12-08.05.58.35.17c26fba
          ports:
            - containerPort: 80
